wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.4
    cli_version: 0.17.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1719314435
    t:
      1:
      - 1
      - 5
      - 41
      - 48
      - 53
      - 55
      - 100
      3:
      - 23
      4: 3.12.4
      5: 0.17.3
      8:
      - 5
      13: linux-x86_64
